---
- hosts: localhost
  connection: local
  become: yes
  vars_files:
    - ../../vars/default.yaml

  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages for Docker
      apt: name={{ minikube_required_packages }} state=latest update_cache=yes

    - name: Verify if Reboot Needed
      shell: '[ -f /var/run/reboot-required ] && sudo reboot -f'

    - name: Install Minikube
      get_url:
        url: "{{ minikube_url }}"
        dest: /usr/local/bin/minikube
        mode: u+x,g+x,o+x

    - name: Download the latest release with the command
      command: curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"

    - name: Install Kubectl
      command: sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
