---
- hosts: all
  #become: true
  #become_method: sudo
  #remote_user: rosthansilva
  become_user: rosthansilva   
  vars:
    - admin_user: null
  tasks:
    - name: Install ZSH
      become: yes
      apt:
        name: zsh
        state: latest

    - name : Dell Oh My ZSH anterior
      command: rm -rf /home/{{ admin_user }}/.oh-my-zsh/

    - name: Download zsh installer
      get_url:
        url: https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh
        dest: /tmp/zsh-installer.sh
        mode: u=rwx,g=rx,o=rx
        owner: "{{ admin_user }}"

    - name: Execute the zsh-installer.sh
      shell: /tmp/zsh-installer.sh

    - name: Remove the zsh-installer.sh
      file:
        path: /tmp/zsh-installer.sh
        state: absent


    - name: create fira code script
      copy:
        dest: "/tmp/firacode.sh"
        content: |
          #!/usr/bin/env bash

          fonts_dir="${HOME}/.local/share/fonts"
          if [ ! -d "${fonts_dir}" ]; then
          echo "mkdir -p $fonts_dir"
          mkdir -p "${fonts_dir}"
          else
              echo "Found fonts dir $fonts_dir"
          fi

          version=5.2
          zip=Fira_Code_v${version}.zip
          curl --fail --location --show-error https://github.com/tonsky/FiraCode/releases/download/${version}/${zip} --output ${zip}
          unzip -o -q -d ${fonts_dir} ${zip}
          rm ${zip}

          echo "fc-cache -f"
          fc-cache -f
        mode: u=rwx,g=rx,o=rx
        owner: "{{ admin_user }}"

    - name: Run Script
      command: /tmp/firacode.sh

    - name: instalando Extenções do ZSH fzf
      shell: |
        git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
        ~/.fzf/install
      args:
        chdir: /tmp/

    - name: Install Oh-My-zsh for users
      git:
        repo: "{{ item.repo }}"
        dest: "/home/{{ admin_user }}/.oh-my-zsh/{ item.dir }"
        update: no
      loop:
        - { repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git', dir: 'custom/plugins/zsh-syntax-highlighting' }
        - { repo: 'https://github.com/zsh-users/zsh-autosuggestions', dir: 'custom/plugins/zsh-autosuggestions' }
        - { repo: 'https://github.com/supercrabtree/k', dir: 'custom/plugins/k' }
        - { repo: 'https://github.com/denysdovhan/spaceship-prompt.gi', dir: 'themes/spaceship-prompt' }

    - name: Set default shell for users
      become: yes
      user:
        name: '{{ admin_user }}'
        shell: /bin/zsh

    - name : Instalando Extenção
      template :
        src: ./zsh.template
        dest: "/home/{{ admin_user }}/.zshrc"
