---
- hosts: localhost
  connection: local
  become: yes
  vars_files:
    - ../vars/default.yaml
  
    - name: Update software cache for apt-get
      become: True
      apt:
        update_cache: yes
      changed_when: False

      - name: Download ASC file
      apt_key:
        url: "{{ vscode_microsoft_asc_url }}"
        state: present

    - name: Copy repo list
      ansible.builtin.copy:
        src: files/vscode.list
        dest: /etc/apt/sources.list.d/teams.list
        mode: '0644'

    - name: Update software cache for apt-get again
      become: True
      apt:
        update_cache: yes
      changed_when: False

    - name: Install ms-teams
      apt:
        name: teams
        state: present